version: '3.4'

services:

  iam.db: 
    container_name: iam.db
    environment:
        ACCEPT_EULA: "Y"
        SA_PASSWORD: "Abc@@123"
    restart: always
    ports:
        - "1435:1433"

  iam.api:
    container_name: iam.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=Server=iam.db;Database=iam.db;User Id=sa;Password=Abc@@123;"
      - "IdentityServer:IssuerUri=http://iam.api"
      - "IdentityOptions:Authority=http://iam.api"
    depends_on:
      - iam.db
    ports:
      - "8011:80"