version: '3.4'

services:

  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
        - "5672:5672"
        - "15672:15672"

  redis.db: 
    container_name: redis.db
    restart: always
    ports:
      - "6379:6379"

  iam.db: 
    container_name: iam.db
    environment:
        ACCEPT_EULA: "Y"
        SA_PASSWORD: "Abc@@123"
    restart: always
    ports:
        - "1435:1433"

  pitch.db: 
    container_name: pitch.db
    environment:
        ACCEPT_EULA: "Y"
        SA_PASSWORD: "Abc@@123"
    restart: always
    ports:
        - "1436:1433"

  order.db: 
    container_name: order.db
    environment:
        ACCEPT_EULA: "Y"
        SA_PASSWORD: "Abc@@123"
    restart: always
    ports:
        - "1437:1433"
        

  pitchfinder.gateway:
    container_name: pitchfinder.gateway
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - iam.api
      - pitch.api
    ports:
      - "8090:80"

  iam.api:
    container_name: iam.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - iam.db
    ports:
      - "8011:80"


  pitch.api:
    container_name: pitch.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - pitch.db
    ports:
      - "8012:80"


  pitch.grpc:
    container_name: pitch.grpc
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - pitch.db
    ports:
      - "8013:80"

  order.api:
    container_name: order.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - order.db
    ports:
      - "8014:80"

  order.grpc:
    container_name: order.grpc
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - order.db
    ports:
      - "8015:80"

  payment.momo:
    container_name: payment.momo
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8016:80"
