version: '3.4'

services:
  iam.db: 
    container_name: iam.db
    environment:
        ACCEPT_EULA: "Y"
        SA_PASSWORD: "Abc@@123"
    restart: always
    ports:
        - "1435:1433"

  iam.api:
    container_name: iam.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - iam.db
    ports:
      - "8011:80"

  pitchfinder.gateway:
    container_name: pitchfinder.gateway
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - iam.api
    ports:
      - "8090:80"
