version: '3.4'

services:

  iam.db:
    image: mcr.microsoft.com/mssql/server:2017-latest

  pitch.db:
    image: mcr.microsoft.com/mssql/server:2017-latest

  order.db:
    image: mcr.microsoft.com/mssql/server:2017-latest

  iam.api:
    image: ${DOCKER_REGISTRY-}iamapi
    build:
      context: .
      dockerfile: Services/IAM/IAM.API/Dockerfile

  pitch.api:
    image: ${DOCKER_REGISTRY-}pitchapi
    build:
      context: .
      dockerfile: Services/Pitch/Pitch.API/Dockerfile

  pitchfinder.gateway:
    image: ${DOCKER_REGISTRY-}pitchfindergateway
    build:
      context: .
      dockerfile: APIGateway/PitchFinder.Gateway/Dockerfile
      
  rabbitmq:
    image: rabbitmq:3-management-alpine

