version: '3.4'

services:
  redis.db: 
    container_name: redis.db
    restart: always
    ports:
      - "6379:6379"

  iam.db: 
    container_name: iam.db
    environment:
        ACCEPT_EULA: "Y"
        SA_PASSWORD: "Abc@@123"
    restart: always
    ports:
        - "1435:1433"

  pitch.db: 
    container_name: pitch.db
    environment:
        ACCEPT_EULA: "Y"
        SA_PASSWORD: "Abc@@123"
    restart: always
    ports:
        - "1436:1433"

  order.db: 
    container_name: order.db
    environment:
        ACCEPT_EULA: "Y"
        SA_PASSWORD: "Abc@@123"
    restart: always
    ports:
        - "1437:1433"

  iam.api:
    container_name: iam.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - iam.db
    ports:
      - "8011:80"


  pitch.api:
    container_name: pitch.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - pitch.db
    ports:
      - "8012:80"


  pitchfinder.gateway:
    container_name: pitchfinder.gateway
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - iam.api
      - pitch.api
    ports:
      - "8090:80"

  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
        - "5672:5672"
        - "15672:15672"