version: '3.4'

services:
  redis.db:
    image: redis:alpine

  rabbitmq:
    image: rabbitmq:3-management-alpine

  iam.db:
    image: mcr.microsoft.com/mssql/server:2017-latest

  pitch.db:
    image: mcr.microsoft.com/mssql/server:2017-latest

  order.db:
    image: mcr.microsoft.com/mssql/server:2017-latest

  pitchfinder.gateway:
    image: ${DOCKER_REGISTRY-}pitchfindergateway
    build:
      context: .
      dockerfile: APIGateway/PitchFinder.Gateway/Dockerfile

  iam.api:
    image: ${DOCKER_REGISTRY-}iamapi
    build:
      context: .
      dockerfile: Services/IAM/IAM.API/Dockerfile


  pitch.api:
    image: ${DOCKER_REGISTRY-}pitchapi
    build:
      context: .
      dockerfile: Services/Pitch/Pitch.API/Dockerfile


  pitch.grpc:
    image: ${DOCKER_REGISTRY-}pitchgrpc
    build:
      context: .
      dockerfile: Services/Pitch/Pitch.Grpc/Dockerfile


  order.api:
    image: ${DOCKER_REGISTRY-}orderapi
    build:
      context: .
      dockerfile: Services/Order/Order.API/Dockerfile


  order.grpc:
    image: ${DOCKER_REGISTRY-}ordergrpc
    build:
      context: .
      dockerfile: Services/Order/Order.Grpc/Dockerfile


  payment.momo:
    image: ${DOCKER_REGISTRY-}paymentmomo
    build:
      context: .
      dockerfile: Services/Payment/Payment.Momo/Dockerfile

